name: test-coverage

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # get  code
      - uses: actions/checkout@v4

      #  intall R
      - uses: r-lib/actions/setup-r@v2

      # install dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: "Imports, Suggests"
          extra-packages: "covr"

      # run test and upload coverage
      - name: Run tests and coverage
        run: Rscript -e 'covr::codecov()'
